version: '3.8'

services:
  devsistem-audio-server:
    build: .
    container_name: devsistem-audio-server
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./storage:/app/storage
      - ./db.json:/app/db.json
    environment:
      - PORT=3000
      - BASE_URL=http://audio.seudominio.com
      - NODE_ENV=production
